export enum NotificationType {
  USER_CREATED = "USER_CREATED",
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_STATUS_UPDATED = "TASK_STATUS_UPDATED",
  TASK_DELETED = "TASK_DELETED",
}
